compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  grafana-ml:
    npmRegistryServer: https://us-npm.pkg.dev/grafanalabs-dev/ml-npm-dev/
    npmAlwaysAuth: true
